[package]
name = "rust-frontend"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.17"
yew-router = "0.14.0"
log = "0.4.6"
wasm-logger = "0.2.0"